# Generated by Django 4.0.5 on 2022-08-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chartType',
            field=models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('bubble', 'Bubble'), ('pie', 'Pie')], default='line', max_length=60),
        ),
    ]
