# Generated by Django 4.0.5 on 2022-08-18 19:53

import auth_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_alter_chart_charttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='style',
            field=models.JSONField(default=auth_system.models.Chart.default_style),
        ),
    ]
